# Dependencies

highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Carson Pence
tagline:          ''
description:      ''
#url:              http://cnpence.github.io
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
gems:             [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
